### PR TITLE
Added a file with 22k english 5-letter words for the input options

### PR DESCRIPTION
**Pull request by JamesL813**
allows more common words to be used as input

### CODE REVIEW

**Comment by ivanjermakov** [comment]
Thank you for your contribution!

I have different vision for the project though:
- Please check out #4 and #5. `dev` branch already supports custom dictionary with `-t` and `-g` options
- And since you can specify words with length other than 5 (`-l` option), dictionary with only 5-letter words won't work
- [`en-84k.txt`](https://github.com/ivanjermakov/wordle/blob/master/resource/dict/en-84k.txt) already contains 5794 5-letter words, which seems to be enough

Other than that, I like the idea of expanding guess word dictionary, so we can just append 84-k file with yours for 5-letter words. Can you provide the source of the `en-22k-5l.txt` and `en-1k-5l.txt`?

**Comment by JamesL813** [comment]
Ah ok, I didn't realize the length could be specified! I whipped this up last night in like an hour after realizing one of my go-to words wasn't recognized haha. 

en-1k-51.txt is just your original 10k cut down to 5-letter words only so it's pretty much useless. 

en-22k-5l.txt is cut down from a much larger list of 466,550 words to just the 5-letter words. That original list is probably the most useful thing, I can make a version of that list with no punctuation or acronyms and upload that in a new PR with none of the code changed.

This project is super cool! Thanks for taking the time to look!

**Comment by ivanjermakov** [comment]
You can use the `dev` branch version already: it uses 84k dict for guess words and I'm sure your go-to words will be there :)

Where did you get those files from (or filtered from)? More extensive dictionaries might be useful in the future.

**Comment by JamesL813** [comment]
just installed that, it works great! I just created another PR in the dev branch with the word libraries I found/modified if you're interested!

**Pull request closed without merging**
